### PR TITLE
restructuring interface

### PR DESCRIPTION
**Pull request by Ibnyahyah**

### CODE REVIEW

**Comment by Ibnyahyah** [comment]
I wish to contribute to this projects both in the user interface and the functionality.

**Comment by ksaitor** [comment]
#### 📝 Changed routes:


| [**/**](https://rinkebyfaucet-eyt2iktt0-cryptojobslist.vercel.app/) |
|:-:|
|<a href="https://rinkebyfaucet-eyt2iktt0-cryptojobslist.vercel.app/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/aivaMv3iARBSacRVam7-VZdkyS0hWkYr9m4OF7NzAQHwrAwWVoe5h3p7TNGmCbf1Mk1PAdzo9ecT7MOwTNU4UQ.png">(view full size)</a> |







Commit 049a4315e4cd5c3744f78985b54ac703d583a79b (https://rinkebyfaucet-eyt2iktt0-cryptojobslist.vercel.app).

**Comment by ksaitor** [comment]
Thanks for the contribution! A few notes:

- [ ] Doesn't look great in dark mode. 
- [ ] I'd revert address input. Previous version was simpler and more elegant.
- [ ] Footer alignment is off. Needs simplification. Text should be aligned to the right. No need to the separator. Should not overflow the page height.

image

image

**Comment by Ibnyahyah** [comment]
Do you mean the header should be like align-left?
image

and should their be shadows in the dark mode too and also the color of the border for the input will be blue.

**Comment by Ibnyahyah** [comment]
The footer is okay now. but if the footer is not usefull i can just remove it 
image

**Pull request closed without merging**
